/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19;

/**
 *
 * @author oscar
 */
public class inicioAdministrados extends javax.swing.JFrame {

    /**
     * Creates new form inicioAdministrados
     */
    public inicioAdministrados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistroPaciente = new javax.swing.JToggleButton();
        RegistroVacuna = new javax.swing.JToggleButton();
        btnRegistroFarmacia = new javax.swing.JToggleButton();
        btnRegistroAdministrador = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JButton();
        btnRegresarMenuPrinc = new javax.swing.JButton();
        btnRegistroHospital = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnRegistroPaciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroPaciente.setText("Registro paciente");
        btnRegistroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroPaciente);
        btnRegistroPaciente.setBounds(400, 320, 212, 62);

        RegistroVacuna.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegistroVacuna.setText("Registro vacunas");
        RegistroVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroVacunaActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroVacuna);
        RegistroVacuna.setBounds(400, 460, 212, 61);

        btnRegistroFarmacia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroFarmacia.setText("Registro farmacias");
        btnRegistroFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroFarmaciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroFarmacia);
        btnRegistroFarmacia.setBounds(400, 390, 212, 60);

        btnRegistroAdministrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroAdministrador.setText("Registro usuario");
        btnRegistroAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroAdministrador);
        btnRegistroAdministrador.setBounds(400, 530, 212, 60);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(730, 790, 173, 60);

        btnRegresarMenuPrinc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresarMenuPrinc.setText("Regresar al menu principal");
        btnRegresarMenuPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenuPrinc);
        btnRegresarMenuPrinc.setBounds(70, 790, 310, 60);

        btnRegistroHospital.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistroHospital.setText("Registro hospitales");
        btnRegistroHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroHospital);
        btnRegistroHospital.setBounds(400, 600, 210, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid19/imagenfONDO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-90, 200, 1334, 844);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPacienteActionPerformed
       pacienteRegistro pac = new  pacienteRegistro();
        pac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroPacienteActionPerformed

    private void RegistroVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroVacunaActionPerformed
      registroVacuna vac = new registroVacuna();
      vac.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_RegistroVacunaActionPerformed

    private void btnRegistroFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroFarmaciaActionPerformed
        registroFarmacia pac = new  registroFarmacia();
        pac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroFarmaciaActionPerformed

    private void btnRegistroAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAdministradorActionPerformed
        registroUsuario pac = new  registroUsuario();
        pac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroAdministradorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarMenuPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincActionPerformed
        Ingreso pac = new  Ingreso();
        pac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuPrincActionPerformed

    private void btnRegistroHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroHospitalActionPerformed
          registroHospitales vac = new  registroHospitales();
        vac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroHospitalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioAdministrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton RegistroVacuna;
    private javax.swing.JToggleButton btnRegistroAdministrador;
    private javax.swing.JToggleButton btnRegistroFarmacia;
    private javax.swing.JButton btnRegistroHospital;
    private javax.swing.JToggleButton btnRegistroPaciente;
    private javax.swing.JButton btnRegresarMenuPrinc;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
