/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19;

import Controladores.UsuariosJpaController;
import Entidades.Usuarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class registroUsuariosPacienteAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form registroUsuariosPacienteAdministrador
     */
    public registroUsuariosPacienteAdministrador() {
        initComponents();
    }
 
//    
    private void limpiar(){
        txtNombreUsuarioRegistro.setText("");
        txttContraseñaUsuarioRegistro.setText("");
        buttonGroup1.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreUsuarioRegistro = new javax.swing.JTextField();
        txttContraseñaUsuarioRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRegresarMenuPrinc = new javax.swing.JButton();
        RBadministrador = new javax.swing.JRadioButton();
        RBpaciente = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1387, 900));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 200, 74, 24);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 250, 107, 24);

        txtNombreUsuarioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreUsuarioRegistro);
        txtNombreUsuarioRegistro.setBounds(490, 200, 246, 30);

        txttContraseñaUsuarioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttContraseñaUsuarioRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txttContraseñaUsuarioRegistro);
        txttContraseñaUsuarioRegistro.setBounds(490, 250, 245, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 20, 300, 50);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Registrarme");
        btnAgregar.setToolTipText("");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(270, 710, 170, 38);

        jLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLimpiar.setText("limpiar campos");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jLimpiar);
        jLimpiar.setBounds(450, 710, 148, 38);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(930, 710, 120, 38);

        btnRegresarMenuPrinc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresarMenuPrinc.setText("Regresar al menu principal");
        btnRegresarMenuPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenuPrinc);
        btnRegresarMenuPrinc.setBounds(610, 710, 310, 40);

        RBadministrador.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBadministrador);
        RBadministrador.setText("Administrador");
        getContentPane().add(RBadministrador);
        RBadministrador.setBounds(520, 300, 120, 28);

        RBpaciente.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBpaciente);
        RBpaciente.setText("Usuario");
        getContentPane().add(RBpaciente);
        RBpaciente.setBounds(520, 340, 76, 28);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Tipo de usuario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 310, 150, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenFondo/imagenfONDO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 6, 1270, 844);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioRegistroActionPerformed

    private void txttContraseñaUsuarioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttContraseñaUsuarioRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttContraseñaUsuarioRegistroActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        Usuarios us = new Usuarios();
        us.setUsuario(txtNombreUsuarioRegistro.getText());
        us.setPassword(txttContraseñaUsuarioRegistro.getText());
        int TipoAdmin;
        TipoAdmin = (RBadministrador.isSelected())?1:2;
        us.setUserId(TipoAdmin);
        Controladores.UsuariosJpaController Oscar = new Controladores.UsuariosJpaController();
        Oscar.create(us);
        JOptionPane.showMessageDialog(this, "Usuario agregado exitosamente, para ingresar regresa al menu principal");
        
        limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed


    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
//        limpiar();
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarMenuPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincActionPerformed
        Inicio pac = new  Inicio();
        pac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuPrincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroUsuariosPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroUsuariosPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroUsuariosPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroUsuariosPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroUsuariosPacienteAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBadministrador;
    private javax.swing.JRadioButton RBpaciente;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresarMenuPrinc;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JTextField txtNombreUsuarioRegistro;
    private javax.swing.JTextField txttContraseñaUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
