/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19;

import Controladores.FarmaciaJpaController;
import Entidades.Farmacia;
import Entidades.Hospital;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class registroFarmacia extends javax.swing.JFrame {

    /**
     * Creates new form registroFarmacia
     */
    public registroFarmacia() {
        initComponents();
    }
    
    private void cargaTabla(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Nombre farmacia");
        dtm.addColumn("Municipio");
        dtm.addColumn("Vacuna disponible");
        
       
        Object[] fila = new Object[4];
        FarmaciaJpaController pc = new FarmaciaJpaController();
        List<Farmacia> lista = pc.findFarmaciaEntities();
        for(Farmacia p:lista){
            fila[0]= p.getId();
            fila[1]= p.getNombreFarmacia();
            fila[2]= p.getMunicipio();
            fila[3]= p.getVacunas();
            
     
            dtm.addRow(fila);
            
        }
        tblFarmacia.setModel(dtm);
    }
//    
    private void limpiar(){
        txtNombreFarmacia.setText("");
        cmbMunicipio.setSelectedItem("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFarmacia = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtNombreFarmacia = new javax.swing.JTextField();
        btnRegresarMenuPrinc1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbMunicipio = new javax.swing.JComboBox<>();
        rSI = new javax.swing.JRadioButton();
        rNo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre de farmacia:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 170, 180, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Municipio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 230, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registro farmacias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 0, 320, 80);

        tblFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFarmaciaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblFarmacia);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(150, 460, 560, 250);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(390, 370, 130, 31);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(530, 370, 130, 31);

        jLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLimpiar.setText("limpiar campos");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jLimpiar);
        jLimpiar.setBounds(230, 370, 151, 31);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(40, 370, 170, 31);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(670, 370, 120, 31);
        getContentPane().add(txtNombreFarmacia);
        txtNombreFarmacia.setBounds(300, 180, 190, 30);

        btnRegresarMenuPrinc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresarMenuPrinc1.setText("Regresar al menu principal");
        btnRegresarMenuPrinc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrinc1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenuPrinc1);
        btnRegresarMenuPrinc1.setBounds(270, 720, 310, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Vacunas:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 290, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Municipio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 230, 110, 30);

        cmbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Zapopan", "Guadalajara", "Tlaquepaque", "El salto", "Ixtlahuacan", "Tlajomulco de zuñiga", "Juanacatlan", "Tonala", "Zapotlanejo" }));
        getContentPane().add(cmbMunicipio);
        cmbMunicipio.setBounds(300, 230, 130, 30);

        rSI.setText("Si");
        rSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSIActionPerformed(evt);
            }
        });
        getContentPane().add(rSI);
        rSI.setBounds(290, 290, 33, 23);

        rNo.setText("No");
        rNo.setToolTipText("");
        getContentPane().add(rNo);
        rNo.setBounds(400, 290, 40, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid19/imagenfONDO.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 920, 844);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFarmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFarmaciaMouseClicked
//        int renglon = tblFarmacia.getSelectedRow();
//        txtNombreVacuna.setText(tblFarmacia.getValueAt(renglon, 1).toString());
//        txtCantidadVacunas.setText(tblFarmacia.getValueAt(renglon, 2).toString());
//
//        btnModificar.setEnabled(true);
//        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblFarmaciaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

//        int renglon = tblFarmacia.getSelectedRow();
//        int id =  (int)tblFarmacia.getValueAt(renglon, 0);
//        Vacunas us = new Vacunas();
//        us.setId(id);
//        us.setNombreDeVacuna(txtNombreVacuna.getText());
//        us.setCantidad(Integer.parseInt(txtCantidadVacunas.getText()));
//
//        VacunasJpaController oscar = new VacunasJpaController();
//        try {
//            oscar.edit(us);
//            limpiar();
//            cargaTabla();
//            btnModificar.setEnabled(false); //se desactiva el btn
//        } catch (Exception ex) {
//            Logger.getLogger(pacienteRegistro.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

//        int renglon = tblFarmacia.getSelectedRow();
//        int id =  (int)tblFarmacia.getValueAt(renglon, 0);
//        VacunasJpaController oscar = new VacunasJpaController();
//        try {
//            oscar.destroy(id);
//            limpiar();
//            cargaTabla();
//            btnEliminar.setEnabled(false); //desactivar el btn
//        } catch (NonexistentEntityException ex) {
//            Logger.getLogger(pacienteRegistro.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //
        Farmacia far = new Farmacia();
        far.setNombreFarmacia(txtNombreFarmacia.getText());
        far.setMunicipio(cmbMunicipio.getSelectedItem().toString());
        char vacuna;
        vacuna = (rSI.isSelected())?'SI':'NO';
        far.setVacunas(vacunas);
        
        Controladores.VacunasJpaController Oscar = new Controladores.VacunasJpaController();
        Oscar.create(far);
        JOptionPane.showMessageDialog(this, "Vacuna agregada exitosamente");
        cargaTabla();
        limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarMenuPrinc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrinc1ActionPerformed
        inicioAdministrados pac = new  inicioAdministrados();
        pac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuPrinc1ActionPerformed

    private void rSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroFarmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresarMenuPrinc1;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rNo;
    private javax.swing.JRadioButton rSI;
    private javax.swing.JTable tblFarmacia;
    private javax.swing.JTextField txtNombreFarmacia;
    // End of variables declaration//GEN-END:variables
}
