/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19;


import Controladores.HospitalJpaController;
import Controladores.VacunasJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Hospital;
import static Entidades.Hospital_.id;
import Entidades.Vacunas;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class registroHospitales extends javax.swing.JFrame {

    /**
     * Creates new form registroHospitales
     */
    public registroHospitales() {
        initComponents();
        cargaTabla();
        limpiar();
        cargaCombo();
    }

    private void cargaTabla(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Nombre del hospital");
        dtm.addColumn("Seguro de gatos medicos");
        dtm.addColumn("ocupacion");
        dtm.addColumn("Vacuna");
        
        
       
        Object[] fila = new Object[5];
        HospitalJpaController pc = new HospitalJpaController();
        List<Hospital> lista = pc.findHospitalEntities();
        for(Hospital p:lista){
            fila[0]= p.getId();
            fila[1]= p.getNombreHospital();
            fila[2]= p.getSeguroDeGatosMedicos();
            fila[3]= p.getOcupacion();
            fila[4]= p.getIdVacunaHospitales().getNombreDeVacuna();
            
     
            dtm.addRow(fila);
            
        }
        tblHospital.setModel(dtm);
        
    }
    
    public void cargaCombo(){
        
        VacunasJpaController pc = new VacunasJpaController();
        List<Vacunas> lista = pc.findVacunasEntities();
        ComboItem item;
        for(Vacunas p:lista){
            item = new ComboItem(p.getId(), p.getNombreDeVacuna());
            cmbVacuna.addItem(item);
        }
        
    }
//    
    private void limpiar(){
        txtNombreHospital.setText("");
        
        buttonGroup1.clearSelection();
        cmbOcupacion.setSelectedIndex(0);
        cmbVacuna.setSelectedItem(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtNombreHospital = new javax.swing.JTextField();
        btnRegresarMenuPrinc1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Rsi = new javax.swing.JRadioButton();
        Rno = new javax.swing.JRadioButton();
        cmbOcupacion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbVacuna = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1334, 844));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre de hospital:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 160, 180, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Acepta seguro de gastos medicos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 230, 320, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registro hospitales");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 0, 320, 80);

        tblHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHospitalMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHospital);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(170, 440, 1040, 250);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(700, 360, 130, 38);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(840, 360, 130, 38);

        jLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLimpiar.setText("limpiar campos");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jLimpiar);
        jLimpiar.setBounds(530, 360, 148, 38);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(340, 360, 170, 38);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(980, 360, 120, 38);
        getContentPane().add(txtNombreHospital);
        txtNombreHospital.setBounds(590, 170, 190, 30);

        btnRegresarMenuPrinc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresarMenuPrinc1.setText("Regresar al menu principal");
        btnRegresarMenuPrinc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrinc1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenuPrinc1);
        btnRegresarMenuPrinc1.setBounds(600, 720, 310, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ocupacion:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 280, 100, 30);

        Rsi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rsi);
        Rsi.setText("Si");
        getContentPane().add(Rsi);
        Rsi.setBounds(700, 230, 43, 28);

        Rno.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rno);
        Rno.setText("No");
        getContentPane().add(Rno);
        Rno.setBounds(770, 230, 50, 28);

        cmbOcupacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocupacion:", "Alta", "Media", "Baja" }));
        getContentPane().add(cmbOcupacion);
        cmbOcupacion.setBounds(660, 290, 180, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Vacuna:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 320, 70, 30);

        getContentPane().add(cmbVacuna);
        cmbVacuna.setBounds(660, 320, 180, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/covid19/imagenfONDO.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1340, 844);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenFondo/imagenfONDO.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1340, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHospitalMouseClicked
        int renglon = tblHospital.getSelectedRow();
        txtNombreHospital.setText(tblHospital.getValueAt(renglon, 1).toString());
        
        if(tblHospital.getValueAt(renglon, 2).equals('S')){
            Rsi.setSelected(true);
        }else{
            Rno.setSelected(true);
        }
        cmbOcupacion.setSelectedItem(tblHospital.getValueAt(renglon, 3).toString());
        // revisar el de vacunas
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblHospitalMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int renglon = tblHospital.getSelectedRow();
        int id =  (int)tblHospital.getValueAt(renglon, 0);
        Hospital us = new Hospital();
        us.setId(id);
        us.setNombreHospital(txtNombreHospital.getText());
        
       
       
        us.setOcupacion(cmbOcupacion.getSelectedItem().toString());
        int numero = cmbVacuna.getSelectedIndex();
        switch(numero){
            case 0: us.setIdVacunaHospitales(new Vacunas(1));
                    break; 
            case 1: us.setIdVacunaHospitales(new Vacunas(2));
                    break;
            case 2: us.setIdVacunaHospitales(new Vacunas(3));
                    break;
            default: break;
        }
     

        HospitalJpaController oscar = new HospitalJpaController();
        try {
            oscar.edit(us);
            limpiar();
            cargaTabla();
            btnModificar.setEnabled(false); //se desactiva el btn
        } catch (Exception ex) {
            Logger.getLogger(pacienteRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int renglon = tblHospital.getSelectedRow();
        int id =  (int)tblHospital.getValueAt(renglon, 0);
        VacunasJpaController oscar = new VacunasJpaController();
        try {
            oscar.destroy(id);
            limpiar();
            cargaTabla();
            btnEliminar.setEnabled(false); //desactivar el btn
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(pacienteRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //
        Hospital hos = new Hospital();
        hos.setNombreHospital(txtNombreHospital.getText());
        
        hos.setOcupacion(cmbOcupacion.getSelectedItem().toString());
//        hos.setIdVacunaHospitales((Vacunas) cmbVacuna.getSelectedItem());
        hos.setOcupacion(cmbOcupacion.getSelectedItem().toString());
        int numero = cmbVacuna.getSelectedIndex();
        switch(numero){
            case 0: hos.setIdVacunaHospitales(new Vacunas(1));
                    break; 
            case 1: hos.setIdVacunaHospitales(new Vacunas(2));
                    break;
            case 2: hos.setIdVacunaHospitales(new Vacunas(3));
                    break;
            default: break;
        }
        Controladores.HospitalJpaController Oscar = new Controladores.HospitalJpaController();
        Oscar.create(hos);
        JOptionPane.showMessageDialog(this, "Hospital agregada exitosamente");
        cargaTabla();
        limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarMenuPrinc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrinc1ActionPerformed
        inicioAdministrados pac = new  inicioAdministrados();
        pac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuPrinc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroHospitales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rno;
    private javax.swing.JRadioButton Rsi;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresarMenuPrinc1;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbOcupacion;
    private javax.swing.JComboBox<ComboItem> cmbVacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTextField txtNombreHospital;
    // End of variables declaration//GEN-END:variables
}
